orbisgis/h2gis

h2spatial-ext/src/test/java/org/h2gis/h2spatialext/drivers/osm/OSMImportTest.java
Add a test to ensure that the issue #441 works.
=> Add a test for #441 and it works !

release.properties, spatial-utilities/src/main/java/org/h2gis/utilities/TableLocation.java, spatial-utilities/src/test/java/org/h2gis/utilities/TableLocationTest.java
Issue when linking with files starting with a number
=> Quote table not starting with letters

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/properties/ST_Explode.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/SpatialFunctionTest.java, h2spatial/src/main/java/org/h2gis/h2spatial/internal/function/spatial/properties/ColumnSRID.java, spatial-utilities/src/main/java/org/h2gis/utilities/SFSUtilities.java
The ST_Explode function supports now a SELECT query.
```mysql
SELECT * FROM ST_EXPLODE('SELECT * FROM BRETAGNE WHERE DEPARTEMENT=56');
```
Related to #418
=> ST_Explode select query

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/mesh/ST_Voronoi.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/function/spatial/mesh/MeshFunctionTest.java
Empty input does not throw SQLException
=> Fix unit test of Voronoi function. 

h2drivers/src/main/java/org/h2gis/drivers/osm/OSMRead.java, h2drivers/src/main/java/org/h2gis/drivers/osm/ST_OSMDownloader.java
Add a test to support only .osm extension
=> Fix st_downloader

docs/dev/ST_Explode.md
Update the doc to take into acount the new signature with query
Linked with #478
=> Update documentation for ST_Explode

docs/dev/ST_3DLength.md, docs/dev/ST_Length.md, docs/dev/ST_SunPosition.md, docs/dev/geom3D/distance-functions.md
Add web documentation for ST_SunPosition and additional small modifications (links between ST_Length and ST_3DLength)
Linked with #464 
Note that ST_GeometryShadow documentation will be created just after.
=> Add web documentation for ST_SunPosition and additional modifications

docs/dev/ST_SunPosition.md
Add a warning message about the POINT which have to be exprimed in WGS84
=> Add a WGS84 warning to ST_SunPosition

docs/dev/ST_LineFromText.md, docs/dev/ST_LineFromWKB.md, docs/dev/ST_MLineFromText.md, docs/dev/ST_MPointFromText.md, docs/dev/ST_MPolyFromText.md, docs/dev/ST_PointFromText.md, docs/dev/ST_PointFromWKB.md, docs/dev/ST_PolyFromText.md, docs/dev/ST_PolyFromWKB.md
Update documentation for ST_PointFromText, ST_MPointFromText, ST_PLineFromText, ST_MLineFromText, ST_LineFromText, ST_MLineFromText, ST_LineFromWKB and ST_PolyFromWKB
--> now signature can ignore srid parameter.
Add documentation for ST_PointFromWKB
Linked with #501
=> update signatures - srid or not

_includes/from-wkb-desc.html, _includes/from-wkt-desc.html
=> Update html files

_includes/footer.html
=> Update footer icon

_includes/footer.html, _includes/primary-nav-items.html, support/index.html
Add a "Support" page
Resolve the problem of Twitter icon
Sorry for the inappropriate branch name
=> Add support page and update twitter icon

docs/dev/ST_Accum.md
=> Update ST_Accum web documentation

_includes/spatial_indice_warning.html, docs/dev/ST_Contains.md, docs/dev/ST_Covers.md, docs/dev/ST_Crosses.md, docs/dev/ST_Disjoint.md, docs/dev/ST_Equals.md, docs/dev/ST_Intersects.md, docs/dev/ST_Overlaps.md, docs/dev/ST_Touches.md, docs/dev/ST_Within.md
=> update predicates with a spatial warning

docs/dev/ST_LongestLine.md, docs/dev/ST_MaxDistance.md, docs/dev/ST_ProjectPoint.md
=> Add web documentation for ST_MaxDistance

docs/dev/CSVRead.md
=> Update CSVRead - add geometric example

docs/dev/ST_CollectionExtract.md, docs/dev/ST_FlipCoordinates.md, docs/dev/ST_GeometryShadow.md, docs/dev/ST_LineIntersector.md, docs/dev/ST_LineMerge.md, docs/dev/ST_OSMDownloader.md, docs/dev/ST_PointFromWKB.md, docs/dev/ST_ProjectPoint.md, docs/dev/ST_RingSideBuffer.md, docs/dev/ST_SideBuffer.md, docs/dev/ST_SunPosition.md
Update function URLs in order to remove "laste commit id"
@nicolas-f @ebocher
=> Update code source URLs

index.html
Update the number of unit test from 579 to 726
@nicolas-f @ebocher
=> Update homepage with appropriate unit test number

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/mesh/ST_Voronoi.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/function/spatial/mesh/MeshFunctionTest.java
Merge voronoi edges when input is multipoint and chosen output dimension is 1
=> Merge voronoi edges

h2drivers/src/main/java/org/h2gis/drivers/file_table/H2Table.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/CreateSpatialExtension.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/mesh/DelaunayData.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/mesh/ST_Tessellate.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/properties/ST_3DArea.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/properties/ST_3DLength.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/properties/ST_3DPerimeter.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/properties/ST_Perimeter.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/topography/ST_TriangleDirection.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/SpatialFunction2Test.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/SpatialFunctionTest.java, spatial-utilities/src/main/java/org/h2gis/utilities/jts_utils/TriMarkers.java, spatial-utilities/src/main/java/org/h2gis/utilities/jts_utils/tesselate/EarClipper.java
- ST_Perimeter (SQL/MM)
- ST_3DPerimeter
- ST_3DArea
after talking with @gpetit
=> Add new functions

pom.xml
Add maven site generation with version folder
=> Add maven site generation

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/topography/ST_TriangleContouring.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/function/spatial/topography/TopographyTest.java
Was stopping if an input triangle totally outside of iso levels
=> Fix st_trianglecontouring

h2drivers/src/main/java/org/h2gis/drivers/file_table/H2TableIndex.java, h2drivers/src/test/java/org/h2gis/drivers/shp/SHPEngineTest.java
This is for OrbisGIS optimised rowset feature.
=> Add special index flags for speed up ordering on pk column

h2drivers/src/main/java/org/h2gis/drivers/geojson/GeoJsonReaderDriver.java, h2drivers/src/test/java/org/h2gis/drivers/geojson/GeojsonImportExportTest.java
=> GeoJson supports now mixed geometries

h2drivers/src/main/java/org/h2gis/drivers/geojson/GJGeometryReader.java, h2drivers/src/main/java/org/h2gis/drivers/geojson/GeoJsonReaderDriver.java, h2drivers/src/main/java/org/h2gis/drivers/geojson/ST_GeomFromGeoJSON.java, h2drivers/src/test/java/org/h2gis/drivers/geojson/GeojsonImportExportTest.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/CreateSpatialExtension.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/convert/ST_AsGML.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/convert/ST_GeomFromGML.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/convert/ST_GoogleMapLink.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/convert/ST_OSMMapLink.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/SpatialFunction2Test.java, h2spatial/src/main/java/org/h2gis/h2spatial/CreateSpatialExtension.java, h2spatial/src/main/java/org/h2gis/h2spatial/internal/function/spatial/convert/ST_GeomFromWKB.java, h2spatial/src/test/java/org/h2gis/h2spatial/SpatialFunctionTest.java
This PR adds
- ST_GeomFromWKB function about #552 
- ST_AsGML and ST_GeomFromGML functions to be compliant with postgis (Supports only GML 2.1.2)
- ST_GeomFromGeoJSON ready to connect H2GIS with sensors.
- ST_OSMMapLink and ST_GoogleMapLink to generate a map url based on the bounding box of a geometry.
=> New functions

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/convert/ST_GoogleMapLink.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/SpatialFunction2Test.java
Fix the zoom level
Add a new test
=> Fix google map url

doxygen/h2gis.conf, h2-dist/pom.xml
Fix doxygen readme
Add custom PostGIS JDBC driver in H2GIS zip.
=> Doxygen and PostGIS linked table

h2drivers/src/main/java/org/h2gis/drivers/dbf/DBFDriverFunction.java, h2drivers/src/test/java/org/h2gis/drivers/dbf/DBFImportExportTest.java
REAL and DECIMAL type were missing.
=> Fix missing numeric types in DBF driver

h2drivers/pom.xml, h2network/pom.xml, h2spatial-api/pom.xml, h2spatial-ext-osgi/pom.xml, h2spatial-ext/pom.xml, h2spatial-osgi/pom.xml, h2spatial/pom.xml, pom.xml, spatial-utilities/pom.xml, test-utilities/pom.xml
Use the last H2 database engine version 1.4.188
=> Update the last H2 database version

docs/dev/ST_3DArea.md, docs/dev/ST_3DLength.md, docs/dev/ST_3DPerimeter.md, docs/dev/ST_Area.md, docs/dev/ST_SunPosition.md
Add st_3DArea and st_3DPermieter functions
=> Add st_3DArea and st_3DPermieter functions

docs/dev/ST_3DArea.md
Remove SFS reference from ST_3DArea doc
=> Remove SFS reference from ST_3DArea doc

docs/dev/getting-started/Home.md, docs/dev/getting-started/embedded-spatial-db.md, docs/dev/raster/list.md
Updating old git url which referred to the irstv repo
=> Update old git urls

h2drivers/src/main/java/org/h2gis/drivers/DriverManager.java, h2drivers/src/main/java/org/h2gis/drivers/csv/CSVDriverFunction.java, h2drivers/src/main/java/org/h2gis/drivers/dbf/DBFDriverFunction.java, h2drivers/src/main/java/org/h2gis/drivers/geojson/GeoJsonDriverFunction.java, h2drivers/src/main/java/org/h2gis/drivers/gpx/GPXDriverFunction.java, h2drivers/src/main/java/org/h2gis/drivers/kml/KMLDriverFunction.java, h2drivers/src/main/java/org/h2gis/drivers/osm/OSMDriverFunction.java, h2drivers/src/main/java/org/h2gis/drivers/shp/SHPDriverFunction.java, h2spatial-api/src/main/java/org/h2gis/h2spatialapi/DriverFunction.java
Adds to the class **DriverFunction** a method *isSpatialFormat(String extension) : boolean*.
With this methods a driver can tell if the given extension (like *"shp"*, *"csv"*, ...) is recognize as a spatial format or not.
=> Adds isSpatialFormat method to DriverFunction

index.html
=> Update the number of test

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/CreateSpatialExtension.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/raster/ST_D8Slope.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/jai/Area3x3OpImage.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/jai/SlopeDescriptor.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/jai/SlopeOpImage.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/jai/SlopeRIF.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/function/spatial/raster/RasterFunctionTest.java
- Define ST_D8Slope
- Add ST_Area3x3OpImage for future 3x3 operations. It is complicated to remove duplicated code as it is not possible to do type parameters with raw type of java.
=> Add ST_D8Slope

h2spatial/pom.xml, h2spatial/src/main/java/org/h2gis/h2spatial/internal/function/spatial/crs/ST_SetSRID.java, h2spatial/src/main/java/org/h2gis/h2spatial/internal/function/spatial/crs/ST_Transform.java, h2spatial/src/test/java/org/h2gis/h2spatial/CRSFunctionTest.java, h2spatial/src/test/java/org/h2gis/h2spatial/SpatialFunctionTest.java
=> About #646

h2drivers/src/main/java/org/h2gis/drivers/tsv/TSVDriverFunction.java, h2drivers/src/main/java/org/h2gis/drivers/tsv/TSVRead.java, h2drivers/src/main/java/org/h2gis/drivers/tsv/TSVWrite.java, h2drivers/src/test/java/org/h2gis/drivers/tsv/TSVDriverTest.java, h2spatial-ext-osgi/src/main/java/org/h2gis/h2spatialext/osgi/Activator.java, h2spatial-ext/src/main/java/org/h2gis/h2spatialext/CreateSpatialExtension.java
This PR adds a TSVDriver to read Tab-separated values file.
TSVRead and TSVWrite functions could be used in SQL instruction to import or export a TSV file.
=> About #617

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/raster/ST_Extrema.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/function/spatial/raster/RasterFunctionTest.java
Return Double[] instead of double[]
=> About #631

h2drivers/pom.xml, h2drivers/src/main/java/org/h2gis/drivers/geojson/GeoJsonWriteDriver.java, h2drivers/src/main/java/org/h2gis/drivers/kml/KMLWriterDriver.java, h2network/pom.xml, h2spatial-api/pom.xml, h2spatial-ext-osgi/pom.xml, h2spatial-ext/pom.xml, h2spatial-osgi/pom.xml, h2spatial/pom.xml, jts-osgi/pom.xml, pom.xml, spatial-utilities/pom.xml, test-utilities/pom.xml
Revert the PR #648.
Fixes the KML, KMZ, geoJSON drivers.
=> Fixes KML/KMZ and geoJSON driver under postgresql

spatial-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
Adds three functions to the JDBCUtilities : 
- getAllTableNameList() : Returns all the table names.
- gettAllFieldName() : Returns all the field names.
- getFieldValueList() : Returns all the field distinct values.
=> Adds methods to JDBCUtilities

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/properties/ST_3DLength.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/SpatialFunctionTest.java, h2spatial-ext/src/test/java/org/h2gis/h2spatialext/function/spatial/mesh/MeshFunctionTest.java, h2spatial/src/main/java/org/h2gis/h2spatial/internal/function/spatial/properties/ST_Length.java, h2spatial/src/test/java/org/h2gis/h2spatial/SpatialFunctionTest.java
Fix also ST_3DLength. Returns 0 for polygon, multipolygon and mixed collection
=> About  #666

h2drivers/src/main/java/org/h2gis/drivers/dbf/DBFDriverFunction.java
Fix the pk that was null
Add a progress monitor
=> About #1003 on orbisgis issues

h2drivers/pom.xml, h2network/pom.xml, h2spatial-api/pom.xml, h2spatial-ext-osgi/pom.xml, h2spatial-ext/pom.xml, h2spatial-osgi/pom.xml, h2spatial/pom.xml, pom.xml, spatial-utilities/pom.xml, test-utilities/pom.xml
Release 1.2.4 and prepare 1.3.0-SNAPSHOT.
=> Release 1.2.4 and prepare 1.3.0-SNAPSHOT.

pom.xml
Updates the CTS and orbisgis-nexus version.
=> Updates the CTS and orbisgis-nexus version.

h2-dist/pom.xml, h2drivers/pom.xml, h2network/pom.xml, h2spatial-api/pom.xml, h2spatial-ext-osgi/pom.xml, h2spatial-ext/pom.xml, h2spatial-osgi/pom.xml, h2spatial/pom.xml, h2spatialtest/pom.xml, jts-osgi/pom.xml, pom.xml, spatial-utilities/pom.xml, test-utilities/pom.xml
=> Prepare release 1.2.4

h2-dist/pom.xml, h2drivers/pom.xml, h2network/pom.xml, h2spatial-api/pom.xml, h2spatial-ext-osgi/pom.xml, h2spatial-ext/pom.xml, h2spatial-osgi/pom.xml, h2spatial/pom.xml, h2spatialtest/pom.xml, jts-osgi/pom.xml, pom.xml, spatial-utilities/pom.xml, test-utilities/pom.xml
Prepare for next development iteration, change version 1.2.4 to 1.3.0-SNAPSHOT.
=> Prepare for next development iteration

h2gis-ext-osgi/src/main/java/org/h2gis/ext/osgi/Activator.java, h2gis-functions-osgi/pom.xml, h2gis-functions-osgi/src/main/java/org/h2gis/functions/osgi/Activator.java, h2gis-functions-osgi/src/main/java/org/h2gis/functions/osgi/FunctionTracker.java
=> Fix module dependency

h2gis-api/pom.xml, h2gis-ext-osgi/pom.xml, h2gis-ext/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-utilities/pom.xml, pom.xml
=> Prepare release v1.3.0

_posts/2016-06-03-h2gis-1.3.0-released.markdown
Adds the 1.3.0 release markdown post.
=> Adds the 1.3.0 release markdown post.

docs/1.3/getting-started/quickstart.md, docs/Home.md, docs/dev/getting-started/quickstart.md
Updates the instruction on the quick start guide.
Few fixes.
=> Updates the instruction on the quick start guide.

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-ext-osgi/pom.xml, h2gis-ext/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-test/pom.xml, h2gis-utilities/pom.xml, jts-osgi/pom.xml, pom.xml
Prepare for next development iteration
=> H2GIS 1.3.1-SNAPSHOT

h2gis-functions/pom.xml
Try to fix the Cobertura build error.Prepare for next development iteration
=> Try to fix the Cobertura build error.

h2gis-test/pom.xml, h2gis-test/src/test/java/org/h2gis/osgi/test/BundleTest.java
Fixes the dependencies error on h2gis-test.
=> Fixes the dependencies error on h2gis-test.

h2gis-functions/pom.xml, h2gis-test-utilities/pom.xml, h2gis-utilities/pom.xml, pom.xml
Fixes the h2gis-function bundle by removing some h2 packages from Import-Packages.
Updates the version of JTS to 1.14.0 (with jts-core and jts-io dependencies).
=> Fixes the osgi part of H2GIS.

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/aggregate/ST_Accum.java
- Register the ST_Graph function
- Improve ST_Accum documentation
=> Basic fixes

jts-core-osgi/pom.xml, jts-io-osgi/pom.xml, pom.xml
=> Fixes osgi jts modules.

h2gis-test/pom.xml
Fixes the jts-version in the h2gis-test module.
=> Fixes the jts-version in the h2gis-test module.

h2gis-functions/src/main/java/org/h2gis/functions/io/shp/internal/SHPDriver.java
Change File.listFiles() by the JAVA7 method DirectoryStream
to handle directory with a large amount of files
=> ShapeFile driver : List files 

h2gis-functions/src/main/java/org/h2gis/functions/spatial/buffer/ST_SideBuffer.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/processing/ProcessingFunctionTest.java
Return null if the input geometry is null.
=> Fix st_sidebuffer for null geometry

h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUrlParser.java, h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUrlParserTest.java
Very very bad idea.
This PR breaks the datasourcefactory in OrbisGIS
=> Revert #715

h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/internal/SHPDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/utility/ReadBufferManager.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/affine_transformations/ST_Rotate.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/aggregate/ST_Accum.java
Avoid null geometry and add some doc
=> Doc + null geometry 

docs/1.2/raster/list.md, docs/1.3/raster/list.md
Update raster pages for 1.2 and 1.3
Refers to https://github.com/orbisgis/h2gis/issues/694
=> Update raster pages for 1.2 and 1.3

docs/1.2/getting-started/Home.md, docs/1.3/getting-started/Home.md, docs/Home.md, docs/dev/getting-started/Home.md
Update docs home pages
- update introduction textes
- add a link to download the unreleased version of H2GIS (linked with #723 )
- update javadoc url
@ebocher @SPalominos
=> Update docs home pages

docs/dev/getting-started/Home.md
=> Update docs home pages - v2

docs/dev/ST_NumInteriorRings.md
Update ST_NumInteriorRings doc
Refers to #559
=> update ST_NumInteriorRings doc

docs/dev/ST_OSMDownloader.md
Update ST_OSMDownloader doc with "delete" parameter
Resolve a part of #559
=> Update ST_OSMDownloader with delete parameter

docs/dev/ST_GeomFromText.md, docs/dev/ST_GeomFromWKB.md, docs/dev/ST_GeometryTypeCode.md, docs/dev/ST_LineFromWKB.md, docs/dev/ST_PointFromWKB.md, docs/dev/ST_PolyFromWKB.md
Add a doc for ST_GeomFromWKB
Refers to #559
=> Add a doc for ST_GeomFromWKB

docs/dev/GeoJsonRead.md, docs/dev/GeoJsonWrite.md, docs/dev/ST_AsGeoJson.md, docs/dev/ST_AsKML.md, docs/dev/ST_GeomFromGeoJson.md, docs/dev/ST_GeomFromWKB.md, docs/dev/ST_OSMDownloader.md
Add a doc for ST_GeomFromGeoJson function
Refers to #559 
@ebocher
=> Add a doc for ST_GeomFromGeoJson function

docs/dev/ST_Force2D.md, docs/dev/ST_GeomFromGML.md, docs/dev/ST_GeomFromGeoJson.md, docs/dev/ST_GeomFromText.md
Add a doc for ST_GeomFromGML function
Refers to #559 
@ebocher 
NB: don't care about the branch name which is not appropriated
=> Add a doc for ST_GeomFromGML function

docs/dev/ST_AsBinary.md, docs/dev/ST_AsGML.md, docs/dev/ST_AsText.md
Add a doc for ST_AsGML function
Refers to #559 
@ebocher
=> Add a doc for ST_AsGML function

docs/dev/ST_OSMDownloader.md, docs/dev/TSVRead.md, docs/dev/TSVWrite.md
Add docs for TSVRead and TSVWrite functions
Refers to #559 
@ebocher
=> Add docs for TSVRead and TSVWrite functions

h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPEngine.java, h2gis-functions/src/main/java/org/h2gis/functions/io/utility/PRJUtil.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java
=> File table srid

docs/1.3/getting-started/quickstart.md, docs/dev/getting-started/quickstart.md
Update quickstart pages (for dev and 1.3)
=> Update quickstart pages

h2gis-functions/src/main/java/org/h2gis/functions/io/osm/ST_OSMDownloader.java, h2gis-functions/src/test/java/org/h2gis/functions/io/osm/OSMImportTest.java
If the SRID != 4326 than a transformation is applied
=> ST_OSMDownloader now check the srid of the geometry

h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/GPXRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/model/AbstractGpxParserDefault.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/model/GPXTablesFactory.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMTablesFactory.java, h2gis-functions/src/test/java/org/h2gis/functions/io/gpx/GPXImportTest.java
Extend the GPXRead function to allow drop tables
=> About #757

h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/GPXDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/GPXRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMRead.java
OSM and GPX drivers have been refactored to follow the same logic than the  SHP driver
=> OSM and GPX drivers refactoring

h2gis-functions/src/main/java/org/h2gis/functions/io/csv/CSVDriverFunction.java, h2gis-functions/src/test/java/org/h2gis/functions/io/cvs/CSVDriverTest.java
The CSV driver supports the same options as the H2 CSVRead and Write functions.
=> CSV driver supports now options

h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Graph.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/topology/ST_GraphTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
=> ST_Graph supports delete tables option

h2gis-functions/src/main/java/org/h2gis/functions/spatial/edit/ST_RemoveRepeatedPoints.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/CoordinateUtils.java
Now the user can set a tolerance
about #767 
To be documented @gpetit
=> Extend the function ST_RemoveRepeatedPoints

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/edit/ST_RemoveDuplicatedCoordinates.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/edit/ST_RemoveRepeatedPoints.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/CoordinateUtils.java
Now duplicate coordinates (first and last) are removed in case of Linestring, MultiLinestring and MultiPoint
@gpetit
=> About #773

h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_Expand.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Graph.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/create/CreateFunctionTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/topology/ST_GraphTest.java
about ##772
This function has been tested on local and remote database.
To use it 
```java
String url = "jdbc:postgresql://localhost/gisdb";
Properties props = new Properties();
props.setProperty("user", "????");
props.setProperty("password", "????");
Connection con = DriverManager.getConnection(url, props);
try (Statement st = con.createStatement()) {
st.execute("DROP TABLE IF EXISTS TEST; DROP TABLE IF EXISTS TEST_NODES; DROP TABLE IF EXISTS TEST_EDGES");
st.execute("CREATE TABLE test(the_geom GEOMETRY(LINESTRING,0), description VARCHAR, id SERIAL PRIMARY KEY);"
+ "INSERT INTO test VALUES "
+ "('LINESTRING (0 0, 1 2)', 'road1', DEFAULT),"
+ "('LINESTRING (1 2, 2 3, 4 3)', 'road2', DEFAULT),"
+ "('LINESTRING (4 3, 4 4, 1 4, 1 2)', 'road3', DEFAULT),"
+ "('LINESTRING (4 3, 5 2)', 'road4', …
```
=> ST_Graph with PostGIS

docs/dev/GPXRead.md, docs/dev/OSMRead.md, docs/dev/ST_Expand.md, docs/dev/ST_Graph.md, docs/dev/ST_RemoveRepeatedPoints.md
As asked in #765 we have now:
- New signature to remove existing tables for GPXRead, OSMRead and ST_Graph
- Update ST_Graph, which was quite wrong
- Update ST_Expand with new ```distance``` signature
- Update ST_RemoveRepeteadPoints with new ```tolerance``` signature
=> Improve doc for several functions

docs/1.2/ST_Collect.md, docs/1.3/ST_Collect.md, docs/dev/ST_Accum.md, docs/dev/ST_BoundingCircle.md, docs/dev/ST_Collect.md, docs/dev/ST_Expand.md
As asked in #781, add ST_Collect documentation
=> Add ST_Collect documentation

docs/1.2/ST_NPoints.md, docs/1.3/ST_NPoints.md, docs/dev/ST_IsValidReason.md, docs/dev/ST_NPoints.md, docs/dev/ST_NumGeometries.md, docs/dev/ST_NumPoints.md
As asked in #781, 
- Add ST_NPoints doc
- Update ST_NumPoints doc
=> Add ST_NPoints doc

docs/dev/ST_3DLength.md, docs/dev/ST_3DPerimeter.md, docs/dev/ST_Length.md
As asked in #781, update docs for:
- ST_Length and ST_3DLength : now only linestrings are accepted
- ST_3DPerimeter : improve some small things
=> Update Length and Perimeter docs

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-ext-osgi/pom.xml, h2gis-ext/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/DummyTable.java, h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2Table.java, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-test/pom.xml, h2gis-utilities/pom.xml, jts-core-osgi/pom.xml, jts-io-osgi/pom.xml, pom.xml
Prepare the next iteration
H2GIS 1.3.1 must be pushed on Maven Central before merging this PR.
=> Update h2 database

h2gis-test/pom.xml, jts-core-osgi/pom.xml, jts-io-osgi/pom.xml, pom.xml
Adds 'jts-core-osgi' dependency in the 'h2gis-test' pom.
=> Adds 'jts-core-osgi' dependency in the 'h2gis-test' pom.

docs/1.2/DoubleRange.md, docs/1.2/IntegerRange.md, docs/1.2/system/list.md, docs/1.3/DoubleRange.md, docs/1.3/IntegerRange.md, docs/1.3/system/list.md, docs/dev/DoubleRange.md, docs/dev/H2GISversion.md, docs/dev/IntegerRange.md
As asked in #803 , add docs for: 
* DoubleRange 
* IntegerRange
=> Add docs for DoubleRange and IntegerRange

h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_GeomFromText.java, pom.xml
+ a small clean up
I don't know if a new release is needed.
So @nicolas-f and @SPalominos feel free to ping me
=> Update H2 database from 1.4.194 to 1.4.195

h2gis-functions/src/main/java/org/h2gis/functions/spatial/clean/MakeValidOp.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java
=> Improve ST_MakeValid to preserve the geometry dimension

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java
I fixed some typo mistakes and those illogical alternatives.
=> Update GeoJsonReaderDriver class: typo and illogical alternatives

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java
I fixed the writeArray and tested. It worked perfectly!
Now the method writeProperties can write Object field as "{}" and Array field. #819
=> Fix writeArray method and test

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java
=> Add new condition to assure rs.getObject(fieldId) is not null

h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java
=> Add statement to testWriteReadProperties

h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java
Very small changes, just changing 4 lines of codes.
=> Remove casting redundancy in tests

h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPWrite.java, h2gis-functions/src/main/java/org/h2gis/functions/io/utility/PRJUtil.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java
eg. CALL SHPWRITE('/tmp/myfile.shp', 'select the_geom, gid from tableGeom limit 12')
=> Improve SHPWrite function to support select query as argument

h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPWrite.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Explode.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java
about #840
Fix subquery for SHPWrite
Test select from for ST_EXPLODE
=> Fix subquery

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-ext-osgi/pom.xml, h2gis-ext/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-test/pom.xml, h2gis-utilities/pom.xml, jts-core-osgi/pom.xml, jts-io-osgi/pom.xml, pom.xml
=> Prepare release 1.3.2

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_Point.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/create/CreateFunctionTest.java
=> Add ST_POINT alias

h2gis-test/pom.xml
=> Fixes h2gis-test/pom.xml

h2gis-test/pom.xml, h2gis-test/src/test/java/org/h2gis/osgi/test/BundleTest.java
=> Fixes h2gis-test compilation. 

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, h2gis-functions/src/test/resources/org/h2gis/functions/io/geojson/additionalProps.geojson
Fix issue #853 and adds a test for it.
=> Fix issue #853

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java
Add forgotten commit in order to fixes the CRS detection on geojson.
=> Fixes the CRS detection on geojson.

h2gis-functions-osgi/src/main/java/org/h2gis/functions/osgi/Activator.java
Readd the DriverFunctions which were lost on deleting the h2gis-ext modules.
=>  Readd the DriverFunctions. 

h2gis-functions/src/main/java/org/h2gis/functions/io/osm/ST_OSMDownloader.java, h2gis-functions/src/test/java/org/h2gis/functions/io/osm/OSMImportTest.java
=> Fix ST_OSMDownloader

h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java, h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java
Adds a methods to JDBCUtilities to check if a table is linked.
=> JDBCUtilities isLinkedTable

h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/ST_Transform.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/crs/CRSFunctionTest.java
Reset the envelope of the cloned geometry in ST_Transform. Issue #869.
=> Fixes ST_Transform

h2gis-functions/src/test/java/org/h2gis/functions/BasicTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/SFSUtilities.java
A method to simplify the developer's life
=> SFSUtility method

h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Graph.java
Do not used CREATE TEMPORARY TABLE because all indexes are in memory
=> FIX ST_GRAPH to delete temporary tables

docs/1.2/ST_MakeGridPoints.md, docs/1.3.1/ST_MakeGridPoints.md, docs/1.3.2/ST_MakeGridPoints.md, docs/1.3/ST_MakeGridPoints.md, docs/dev/ST_MakeGridPoints.md
Update the doc of ST_MakeGridPoints, as asked in #862
=> Update ST_MakeGridPoints doc

_includes/primary-nav-items.html, users/index.html
As requested in #846 , add a page with tools or projects that are using H2GIS.
=> Add a users doc

users/index.html
=> Add NoiseModelling and NoiseCapture

h2gis-functions/src/main/java/org/h2gis/functions/spatial/topography/TINFeatureFactory.java
This factory must be removed and replaced by the TriMarkers class
=> Remove JDelaunay reference

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topography/ST_Drape.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topography/TINFeatureFactory.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/topography/TopographyTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/TriMarkers.java
The ST_DRAPE function permits to drape a geometry to a set of triangles.
Input geometry to drape : POINT, MULTIPOINT, LINESTRING and POLYGON
Input geometry to compute the planes :  only triangles
Notes : 
In case of linestring or polygon, the input geometry is intersected with the triangles to perform a full draping.
If a point lies on two triangles the z value of the first triangle is kept.
=> St_drape function

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/earth/ST_Svf.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java, h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/CoordinateUtils.java
The function calculates the Sky View Factor for a given point. Needed arguments are point coordinates, obstacle coordinates (Building, trees, etc.), distance of calculation and number of direction. An optional argument can be passed to improve the algorithm speed in certain conditions.
About  #885
=> Sky View Factor function

h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java
=> Fixes tests.

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-test/pom.xml, h2gis-utilities/pom.xml, jts-core-osgi/pom.xml, jts-io-osgi/pom.xml, pom.xml
=> Release vesion 1.4.0.

pom.xml
=> Fix JTS version.

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, pom.xml
=> Fix SQL datatype for geojson write

h2gis-functions-osgi/src/main/java/org/h2gis/functions/osgi/Activator.java, h2gis-functions-osgi/src/main/java/org/h2gis/functions/osgi/DataSourceTracker.java, h2gis-functions-osgi/src/main/java/org/h2gis/functions/osgi/FunctionTracker.java, h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-test-utilities/src/main/java/org/h2gis/unitTest/GeometryAsserts.java, h2gis-utilities/pom.xml, h2gis-utilities/src/main/java/org/h2gis/utilities/TableLocation.java, h2gis-utilities/src/main/java/org/h2gis/utilities/TableUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/URIUtilities.java, h2gis-utilities/src/test/java/org/h2gis/utilities/TableLocationTest.java, h2gis-utilities/src/test/java/org/h2gis/utilities/TableUtilitiesTest.java, h2gis-utilities/src/test/java/org/h2gis/utilities/URIUtilitiesTest.java
Adds test in module h2gis-utilities and increase test coverage. 
Some refactoring.
=> Adds tests

h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTypeCodes.java, h2gis-utilities/src/main/java/org/h2gis/utilities/SFSUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/SpatialResultSet.java, h2gis-utilities/src/main/java/org/h2gis/utilities/SpatialResultSetMetaData.java, h2gis-utilities/src/test/java/org/h2gis/utilities/SFSUtilitiesTest.java, h2gis-utilities/src/test/java/org/h2gis/utilities/TableLocationTest.java
Adds tests on SFSUtilities class.
Improve SFSUtilities javadoc.
Add all the missing geometry codes.
=> Adds tests SFSUtilities.

h2gis-functions/src/main/java/org/h2gis/functions/io/utility/PRJUtil.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/ST_Transform.java
About https://github.com/orbisgis/orbisgis/issues/1326
=> Remove prj message

h2gis-functions/src/main/java/org/h2gis/functions/spatial/volume/GeometryExtrude.java, h2gis-utilities/src/test/java/org/h2gis/utilities/SFSUtilitiesTest.java, pom.xml
Changes the JTS package in order to use the official one.
Adds some tests.
=> Changes the jts package and add some tests.

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/DummyIndex.java, h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2TableIndex.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_OrientedEnvelope.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/create/CreateFunctionTest.java, pom.xml
=> St_OrientedEnvelope

h2gis-functions/src/main/java/org/h2gis/functions/spatial/earth/ST_Isovist.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java, h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/VisibilityAlgorithm.java
Fix, processing of geom collect in geom collect in isovist
=> Fix, processing of geom collect in geom collect in isovist

release_doc.sh
Add a script 'release_doc.sh' which make a release of the documentation with the given version as argument.
Usage : ./release_doc.sh 1.4.0
=> Add a script 'release_doc.sh'

docs/Home.md
Replace last by latest in the home
Thx @nicolas-f
=> Replace last by latest in the home

LICENSE, README.md
Add the LGPLv3 license file.
Add shields to README.md
=> Cosmetic adds

docs/1.2/ST_ShortestLine.md, docs/1.3.1/ST_ShortestLine.md, docs/1.3.2/ST_ShortestLine.md, docs/1.3/ST_ShortestLine.md, docs/1.4.0/ST_ShortestLine.md, docs/dev/SHPWrite.md, docs/dev/ST_ShortestLine.md
As requested in #912 , update the SHPWrite doc to explain how to export the .prj file
In the meantime, just resolve a small typo error for ST_ShortestLine docs
=> Update shpwrite doc to add prj

docs/dev/applications/h2network.md
As requested in #913 add some words about H2Network (and also add two bibliographic ref)
=> Update H2Network page

pom.xml
=> Security alert

h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java
=> ST_XMIN unit test

h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/FileEngine.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/tsv/TSVRead.java, h2gis-functions/src/test/java/org/h2gis/functions/io/cvs/CSVDriverTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFEngineTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/tsv/TSVDriverTest.java
About https://github.com/orbisgis/orbisgis/issues/1308
=> Check file name

docs/dev/SHPWrite.md
As asked in #839 ,update the SHPWrite doc
=> Update the SHPWrite doc

h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/GeometryCoordinateDimension.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_Force2D.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_Force3D.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/edit/ST_UpdateZ.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/convert/ForceDimensionTest.java
This PR update correctly the dimension of the geometry when the st_force2d and st_force3d functions are used.
Note that the coordinate dimension of the geometry will be improved in the future.
Please read 
https://github.com/orbisgis/h2gis/issues/919
https://github.com/orbisgis/h2gis/issues/921
=> About #961

docs/dev/GeoJsonWrite.md
As requested in #954 , update GeoJsonWrite doc
=> update GeoJsonWrite doc

h2gis-functions/pom.xml, h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/SpatialRefRegistry.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/crs/SpatialRegistryTest.java
Linked to https://github.com/orbisgis/cts/pull/110
=> Update epsg registry

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-utilities/pom.xml, pom.xml, postgis-jts-osgi/pom.xml, postgis-jts/pom.xml
=> Release version 1.5.0

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-utilities/pom.xml, pom.xml, postgis-jts-osgi/pom.xml, postgis-jts/pom.xml
=> Next iteration

_posts/2019-03-18-h2gis-1.5.0-released.markdown, docs/1.5.0/ST_Explode.md, docs/dev/ST_Explode.md
* improve the news
* update the doc for ST_Explode (as requested by @ebocher )
=> Update doc for V1.5.0 (v2)

pom.xml
=> Add a standalone profile.

h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/GeometryCoordinateDimension.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java
=> Fix force2D

h2gis-functions/pom.xml, h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/ST_FindUTMSRID.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/crs/CRSFunctionTest.java, h2gis-utilities/pom.xml, h2gis-utilities/src/main/java/org/h2gis/utilities/SFSUtilities.java, pom.xml
Function to return the best UTM srid code for a WGS84 geometry
=> Utm function

h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/internal/DBFDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/internal/DbaseFileReader.java, h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/internal/DBFDriverTest.java
Use long for bytes instead of int
=> Handle DBF file larger than 2.1 Gbytes

h2gis-functions/pom.xml, pom.xml
=> Update h2 1.4.220

h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2Table.java, h2gis-functions/src/main/java/org/h2gis/functions/io/tsv/TSVDriverFunction.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPEngineTest.java
=> Fix spatialtreeindex import

pom.xml
=> Use snapshot version of maven

h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/GeometryCoordinateDimension.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/convert/ForceDimensionTest.java
Make force() method keep the SRID.
=> Make force() method keep the SRID.

h2gis-functions/pom.xml, pom.xml
Fix the usage of our custom H2 build.
=> Fix the usage of our custom H2 build.

h2gis-functions/pom.xml, pom.xml
=> Improve the pom.

postgis-jts/src/main/java/org/h2gis/postgis_jts/JtsBinaryParser.java
Try to fix null pointer exception ont postgis jts module.
Linked to orbisgis/orbisdata#186.
=> Try to fix null pointer exception.

h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/GeographyUtils.java, h2gis-utilities/src/test/java/org/h2gis/utilities/GeographyUtilsTest.java
This PR add a method to extend an envelope expressed in lat/lon with a distance in meters.
It adds also a method to compute the harvesine distance (in meters) between two
coordinates in lat/lon
=> Geography utils

h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_Union.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/predicates/ST_Intersects.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Polygonize.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/processing/ProcessingFunctionTest.java
=> Fix function that doesn't manage well the SRID

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonField.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, h2gis-functions/src/test/resources/org/h2gis/functions/io/geojson/urn_crs84.geojson, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
About https://github.com/orbisgis/geoclimate/issues/266
=> Fix geojson null values

h2gis-functions-osgi/pom.xml, pom.xml
=> Prepare for release RC1.

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-utilities/pom.xml, pom.xml, postgis-jts-osgi/pom.xml, postgis-jts/pom.xml
=> Release version 2.0.0-RC1.

h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/GridRowSet.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/create/CreateFunctionTest.java, h2gis-network/src/main/java/org/h2gis/network/functions/ST_ShortestPath.java, h2gis-network/src/main/java/org/h2gis/network/functions/ST_ShortestPathTree.java
=> Fix JAVA_OBJECT type.

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-utilities/pom.xml, pom.xml, postgis-jts-osgi/pom.xml, postgis-jts/pom.xml
=> Pass to SNAPSHOT.

h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/wrapper/ConnectionWrapper.java, h2gis-utilities/src/main/java/org/h2gis/utilities/wrapper/DataSourceWrapper.java, h2gis-utilities/src/main/java/org/h2gis/utilities/wrapper/ResultSetWrapper.java, h2gis-utilities/src/main/java/org/h2gis/utilities/wrapper/StatementWrapper.java, h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java
H2GIS should work with at least java 7 as H2 database
=> Enable java 6 limitation on the wrapper.

h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/FileEngine.java
fix unlimited loop about #1051
=> fix unlimited loop about #1051

h2gis-functions/pom.xml, h2gis-functions/src/test/java/org/h2gis/functions/BaseTest.java
Add BaseTest class which contains pre-defined geometries and utility tests.
=> Add BaseTest class which aim to simplify the tests

.travis.yml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-utilities/pom.xml, pom.xml, postgis-jts-osgi/pom.xml
Add information about nexus repository in main pom.
=> Add information about nexus repository in main pom.

h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/GridRowSet.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MakeGrid.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MakeGridPoints.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/create/CreateFunctionTest.java
=> Fix SRID on creategrid function

h2gis-functions/src/main/java/org/h2gis/functions/io/DriverManager.java, h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/csv/CSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/GPXDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/model/AbstractGpxParserDefault.java, h2gis-functions/src/main/java/org/h2gis/functions/io/kml/KMLWriterDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMParser.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/tsv/TSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/GridRowSet.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Explode.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topography/ST_TriangleContouring.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Graph.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/SFSUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/TableUtilities.java, h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java, h2gis-utilities/src/test/java/org/h2gis/utilities/TableUtilitiesTest.java
Part of the PR https://github.com/orbisgis/h2gis/pull/1066
=> Improve isH2 method to avoid metadata call

h2gis-functions-osgi/src/main/java/org/h2gis/functions/osgi/DataSourceTracker.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/model/AbstractGpxParserDefault.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMParser.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Graph.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/topology/ST_GraphTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/TableUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/Tuple.java, h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java
Part of https://github.com/orbisgis/h2gis/pull/1066
=> Limit the use of DatabaseMetaData

h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Explode.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topography/ST_TriangleContouring.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Graph.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java
add getGeometryColumnNames method
=> Return linkedhasmap instead of array of tuple

h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_LineFromWKB.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_PointFromWKB.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_PolyFromWKB.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_CoordDim.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_GeometryType.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_GeometryTypeCode.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Is3D.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_SRID.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/processing/ProcessingFunctionTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryMetaData.java
=> Fix POSTGIS issues with drivers

h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/model/AbstractGpxParserDefault.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/model/GPXTablesFactory.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/tsv/TSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_PolyFromWKB.java, h2gis-functions/src/test/java/org/h2gis/functions/io/asc/AscReaderDriverTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/cvs/CSVDriverTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/gpx/GPXImportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/tsv/TSVDriverTest.java, postgis-jts/pom.xml
=> Fix all drivers with postgis

h2gis-functions/src/main/java/org/h2gis/functions/io/json/JsonDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/json/JsonWrite.java, h2gis-functions/src/main/java/org/h2gis/functions/io/json/JsonWriteDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/json/JsonImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/json/JsonWriteDriverTest.java
Improve, add test and fix zip compression of JsonWriterDriver.
=> Improve, add test and fix zip compression of JsonWriterDriver.

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java
=> Add method hasGeometryColumn on table location

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java
Make postgresl disable instead of success when no postresql db.
=> Make postgresl disable instead of success when no postresql db.

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java, h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java
Add method to create a basic create table ddl command from a table or a resultset
Add method to return the table type
Fix in geometry metadata utilities
Linked to https://github.com/orbisgis/orbisdata/issues/270
=> DDL command method + fixes

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
Usefull to build a command table compatible from one db to the other one
=> Improve DDL to manage the source and target table name

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java
About https://github.com/orbisgis/h2gis/issues/1101
=> Add methods to return an extent based on several columns

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java
About https://github.com/orbisgis/h2gis/issues/1104
Fix potential null pointer on geometry
=> Fix envelope and check if the geometry is not null

h2gis-api/src/main/java/org/h2gis/api/FileDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/internal/DBFDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/internal/DbaseFileReader.java, h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2TableIndex.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/internal/SHPDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java
About #1008 Do not read all columns values when a row object is requested by H2 database.
I haven't done a test bench to see if this change has any impact on performance.
=> Faster SHP and DBF file table

h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscReaderDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/asc/AscReaderDriverTest.java
about #1113  Remove pk constraint name
=> ASCRead improvements

h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscRead.java, h2gis-functions/src/test/java/org/h2gis/functions/io/asc/AscReaderDriverTest.java
Boolean as_polygons were not properly handled (bug introduced by @ebocher :P )
@gpetit #1113
=> fix issue with as_polygons parameter

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java
=> Fix update srid function

h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/GPXRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPRead.java, h2gis-functions/src/main/java/org/h2gis/functions/io/tsv/TSVRead.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/UpdateGeometrySRID.java, h2gis-functions/src/main/java/org/h2gis/functions/system/H2GISversion.java, h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java, h2gis-functions/src/test/java/org/h2gis/functions/io/tsv/TSVDriverTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java
About #1124 , #1127 , #1126 ,  #1123
=> Several fixes for IO functions

h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/csv/CSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/GPXDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/json/JsonDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/kml/KMLDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/tsv/TSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/utility/IOMethods.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPEngineTest.java, h2gis-functions/src/test/java/org/h2gis/functions/utility/IOMethodsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java, postgis-jts/src/main/java/org/h2gis/postgis_jts/Driver.java
- to import, export a file in a database (H2GIS, POSTGIS)
- to export a table from another database (H2GIS, POSTGIS)
- to link a file or table (H2GIS only)
=> Add IO utilities

h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
=> Fix methods visibility.

h2gis-utilities/src/main/resources/META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule, h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java
=> Fix index type for H2 db.

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
Postgresql uses a limited size of varchar
=> Fix max varchar size for postgresql

h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java
when the tablelocation doesn't known the schema. The default schema must be set to PUBLIC.
=> Fix a bug on getSrid method 

h2gis-functions/src/main/java/org/h2gis/functions/io/csv/CSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/ST_AsGeoJSON.java, h2gis-functions/src/main/java/org/h2gis/functions/io/json/JsonDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/json/JsonWriteDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/utility/IOMethods.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/TableLocation.java, h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/CoordinateUtils.java, h2gis-utilities/src/test/java/org/h2gis/utilities/TableLocationTest.java
=> Fix geojson timestamp and decimal place

h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_AsWKT.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/ogc/OGCSpatialFunctionTest.java
About https://github.com/orbisgis/h2gis/issues/1157
```
ST_ASWKT('POINT(1 1)')
-> POINT(1 1)
ST_ASWKT('POINT(1 1 1)')
-> POINT Z(1 1 1)
ST_ASWKT('POINT(1 1 1 2)')
-> POINT ZM(1 1 1 2)
```
=> Return the whole dimension of the coordinates with the ST_AsWKT function

.github/workflows/CI build.yml, .github/workflows/CI release.yml, .github/workflows/CI snapshot.yml
=> Add workflows.

.github/workflows/CI release.yml, .github/workflows/CI snapshot.yml, pom.xml
=> Fix pom for deployment.

h2gis-api/pom.xml, h2gis-dist/pom.xml, h2gis-functions-osgi/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-utilities/pom.xml, postgis-jts-osgi/pom.xml, postgis-jts/pom.xml
=> Fix relativePath in poms.

.github/workflows/CI build.yml, .github/workflows/CI snapshot.yml
=> Fix branch name on workflows.

.github/workflows/CI snapshot.yml, pom.xml
=> Try to fix the snapshot CI.

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, h2gis-functions/src/test/resources/org/h2gis/functions/io/geojson/complex.geojson, pom.xml
Update Jackson lib at the same time
=> Fix inconsistent type check on geojson reader

h2gis-functions/src/main/java/org/h2gis/functions/io/utility/IOMethods.java, h2gis-functions/src/test/java/org/h2gis/functions/utility/IOMethodsTest.java
Related to https://github.com/orbisgis/geoclimate/issues/641
=> Fix upper case extension with IOMethods

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/split/ST_SubDivide.java, h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPEngineTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java
Based on  https://stackoverflow.com/questions/64252638/how-to-split-a-jts-polygon idea, adds a new function to subdivide a geometry in one pass or recursively until each geometry have less than a max_vertices
=> Add ST_SubDivide function

docs/CHANGELOG.md, h2gis-functions/pom.xml, h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/DummyMVTable.java, h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2MVTable.java, h2gis-functions/src/test/java/org/h2gis/functions/RegressionTest.java, h2gis-network/pom.xml, h2gis-test-utilities/pom.xml, h2gis-utilities/pom.xml, postgis-jts/pom.xml
This PR uses a compiled version of H2 avaiable in the org.orbisgis repo.
We will change it when the 2.0.206 will be ready on maven central.
https://github.com/h2database/h2database/releases
=> Fix Create linked table with geometry

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_Force3D.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_Force3DM.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_Force4D.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/edit/ST_UpdateZ.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java
=> About 1242

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscReaderDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/csv/CSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMParser.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/tsv/TSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/utility/IOMethods.java, h2gis-functions/src/test/java/org/h2gis/functions/TestUtilities.java, h2gis-network/src/main/java/org/h2gis/network/functions/ST_ConnectedComponents.java, h2gis-network/src/main/java/org/h2gis/network/functions/ST_GraphAnalysis.java, h2gis-network/src/test/java/org/h2gis/network/functions/ST_GraphAnalysisTest.java
Due to https://github.com/orbisgis/h2gis/pull/1248
=> Fix stupid changes on transaction management

.github/workflows/CI build.yml, .github/workflows/CI release.yml, .github/workflows/CI snapshot.yml, docs/CHANGELOG.md, h2gis-dist/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-tests/pom.xml, h2gis-utilities/pom.xml, pom.xml
Remove slf4j-simple (link to #1261)
Improve workflows
=> Workflows and slf4j-simple

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/metadata/FindGeometryMetadata.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java
Some issues when using reserved keyword as a table name in h2gis
=> Fix view geometry_columns

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/io/csv/CSVDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPDriverFunction.java, h2gis-functions/src/main/java/org/h2gis/functions/io/tsv/TSVDriverFunction.java
Use Oracle https://docs.oracle.com/cd/E11882_01/java.112/e16548/oraperf.htm#JJDBC28752 recommendations
=> Change batch size to use the optimal size 

.github/workflows/CI build.yml, .github/workflows/CI release.yml, .github/workflows/CI snapshot.yml, docs/CHANGELOG.md, h2gis-dist/pom.xml, h2gis-functions/pom.xml, h2gis-network/pom.xml, h2gis-tests/pom.xml, h2gis-utilities/pom.xml, pom.xml
Improve workflow in order to generate and upload assets for the release.
Remove slf4j-simple dependency.
=> Improve workflow, remove slf4j-simple.

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_Multi.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/clean/ST_MakeValidTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/convert/ConvertGeometryTypeTest.java
=> Prepare ST_Multi

.github/workflows/CI_snapshot.yml, h2gis-dist/pom.xml, h2gis-tests/pom.xml
Add snapshot archive production. Linked to #1219
=> Add snapshot archive production

docs/CHANGELOG.md, h2gis-utilities/src/main/java/org/h2gis/utilities/TableLocation.java, h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java, h2gis-utilities/src/test/java/org/h2gis/utilities/TableLocationTest.java
TableLocation.parse should restore a TableLocation.toString() to the initial state
=> TableLocation.parse fix

docs/CHANGELOG.md, h2gis-functions/src/test/java/org/h2gis/functions/RegressionTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/FindGeometryMetadataTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, h2gis-utilities/src/test/java/org/h2gis/utilities/dbtypes/DBUtilsTest.java, postgis-jts/src/test/java/org/h2gis/postgis_jts/PostGIS_JTSTest.java
=> Re-enabled tests.

docs/CHANGELOG.md, h2gis-functions/pom.xml, h2gis-tests/pom.xml, h2gis-utilities/pom.xml, h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java, pom.xml
About https://github.com/orbisgis/h2gis/issues/1289
=> Remove orbisparent

docs/CHANGELOG.md, h2gis-functions/pom.xml, h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java, pom.xml
=> Update to H2 2.1.212

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/metadata/FindGeometryMetadata.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/FindGeometryMetadataTest.java
Fix `FindGeometryMetadata` to handle the case of case-sensitive names
=> Fix `FindGeometryMetadata`

docs/CHANGELOG.md, postgis-jts/src/main/java/org/h2gis/postgis_jts/PostGISDBFactory.java
Make the method `PostGISDBFactory.createDataSource(Properties)` static (linked to #1298)
=> Make the method `PostGISDBFactory.createDataSource(Properties)` static

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_Union.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java
ST_union returns null if the input geom is null, empty if the input geometry is empty
=> Fix null st_union

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Node.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/topology/ST_NodeTest.java
This PR improves st_node to remove duplicate lines.
=> Improve st_node to remove duplicate lines

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java
Fix an issue on writing as geojson a table with a null value typed as`TIME`
=> Fix geojson null TIME writing

docs/CHANGELOG.md, h2gis-functions/src/test/java/org/h2gis/functions/RegressionTest.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java, pom.xml
=> Update H2 to 2.1.214

.github/workflows/CI_snapshot.yml
=> Do not create double zip

h2gis-functions/src/main/java/org/h2gis/functions/io/osm/ST_OSMDownloader.java
Change api osm url "http://api.openstreetmap.org/api/0.6" to https://www.openstreetmap.org/api/0.6
=> Upate api osm url

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_Difference.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_Intersection.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_SymDifference.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_Union.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/ogc/OGCSpatialFunctionTest.java
See the nice explanation here http://lin-ear-th-inking.blogspot.com/2020/10/overlayng-lands-in-jts-master.html
=> Use OverlayNGRobust instead of OverlayNG

docs/CHANGELOG.md, pom.xml
=> Add ESRI defs to spatial_ref_sys.sql

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GJGeometryReader.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/ST_AsGeoJSON.java, h2gis-functions/src/test/java/org/h2gis/functions/utility/GeometryFeatureUtilitiesTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java, h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/GeometryFeatureUtils.java, pom.xml, postgis-jts/pom.xml
Utility to convert a resutset or a query to  JSON map
Fix postgresql CE dep see #1339
=> Geojson utils + postgresql dep

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/mesh/ST_Tessellate.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/mesh/MeshFunctionTest.java
=> Fix empty polygon with ST_Tessellate function

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Graph.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/topology/ST_GraphTest.java
The ST_Graph function is now able to keep a list of columns when the edges are built. This is usefull to switch graph weights for network  analysis.
=> Improve ST_Graph

docs/CHANGELOG.md, h2gis-functions/pom.xml, h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/snap/ST_Project.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/snap/SnapFunctionTest.java, pom.xml
ST_Project function returns a point projected from a point along a geodesic using a given distance and azimuth (bearing) when the input geometry has a SRID equal to 4326. Otherwise project the point in cartesian plan.
=> ST_Project function

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/io/fgb/FGBWriteDriver.java, h2gis-functions/src/main/java/org/h2gis/functions/io/fgb/fileTable/FGBDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/fgb/FGBImportExportTest.java
The data types are not well supported by the FGB driver.
@ebocher
=> FGB driver writer data types

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java, h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java, h2gis-functions/src/test/resources/org/h2gis/functions/io/geojson/road_emptylinestring.geojson
=> Geojson without coordinates jts can't guess coordinate dimension

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/ST_IsGeographicCRS.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/ST_IsProjectedCRS.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/crs/CRSFunctionTest.java
Two functions to check if the CRS of the geometry is projected or geograpphic.
=> ST_IsProjectedCRS and ST_IsGeographicCRS

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/io/osm/WayOSMElement.java
=> OSM Reader

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/topology/ST_Graph.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/topology/ST_GraphTest.java, h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
About #1402
Plus add a check on the input table to find the first autoincremented column.
=> More confortable uses of ST_Graph

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/GridRowSet.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MakeGrid.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MakeGridPoints.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/create/CreateFunctionTest.java
Add an option to order the cells from the upper left corner.
=> ST_MAKEGRID and ST_MAKEGRIDPOINTS order cells

.vscode/settings.json, docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/generalize/ST_SimplifyVW.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/processing/ProcessingFunctionTest.java
This PR addresses issue #1406 by adding ST_SimplifyVW.
=> Added ST_SimplifyV

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_MemSize.java
=> Fix ST_MemSize typo

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/generalize/ST_SimplifyVW.java
=> Fix ST_SimplifyVW doc

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_Force3DM.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java
=> Fix ST_Force3DM

docs/CHANGELOG.md, h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java, h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_M.java, h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java
=> Implement ST_M correctl

docs/CHANGELOG.md, h2gis-graalvm/src/main/java/org/h2gis/graalvm/ResultSetWrapper.java
Corrected a bug where the fetch_all would produce a buffer with the column name instead of the alias if precised. Also, added missing documentation.
=> Corrected a C API fetch bug and a missing documentation
