h2drivers/src/main/java/org/h2gis/drivers/kml/KMLWriterDriver.java
h2spatial/src/main/java/org/h2gis/h2spatial/CreateSpatialExtension.java
h2spatial/src/main/java/org/h2gis/h2spatial/ut/SpatialH2UT.java
h2spatial/src/test/java/org/h2gis/h2spatial/OGCConformance1Test.java
h2spatial/src/test/java/org/h2gis/h2spatial/OGCConformance2Test.java
h2spatial/src/test/java/org/h2gis/h2spatial/OGCConformance3Test.java
h2spatial/src/test/java/org/h2gis/h2spatial/SerializationTest.java
h2spatial/src/test/java/org/h2gis/h2spatial/SpatialFunctionTest.java
h2spatial/src/test/java/org/h2gis/h2spatial/SpatialIndexTest.java
spatial-utilities/src/test/java/org/h2gis/utilities/URIUtilityTest.java

I recognized that some unit tests are not working if they will be executed on windows.
In addition fails the SHPEngineTest.testAddIndexOn test because of the fact that the .mv.db will not be deleted in SpatialH2UT.initDBFile

Unit tests are not working on windows

---

h2-dist/pom.xml
h2drivers/pom.xml
h2network/pom.xml
h2spatial-api/pom.xml
h2spatial-ext-osgi/pom.xml
h2spatial-ext/pom.xml
h2spatial-ext/src/main/java/org/h2gis/h2spatialext/CreateSpatialExtension.java
h2spatial-osgi/pom.xml
h2spatial-osgi/src/main/java/org/h2gis/h2spatial/osgi/Activator.java
h2spatial-osgi/src/main/java/org/h2gis/h2spatial/osgi/DataSourceTracker.java
h2spatial-osgi/src/main/java/org/h2gis/h2spatial/osgi/FunctionTracker.java
h2spatial/pom.xml
h2spatial/src/main/java/org/h2gis/h2spatial/CreateSpatialExtension.java
h2spatialtest/pom.xml
h2spatialtest/src/test/java/org/h2gis/osgi/test/BundleTest.java
jts-osgi/pom.xml
pom.xml
spatial-utilities/pom.xml
test-utilities/pom.xml

The database should already be spatialized before the DataSource is registered in OSGi. Then DataSource tracker of h2spatial should be limited on registering/unregistering additional SQL functions.

Remove osgi datasource auto init

---

pom.xml

Update H2 dependency to the last published version  1.4.186 (2015-03-02), Beta

Update H2 database version

---

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/mesh/ST_Delaunay.java
h2spatial-ext/src/test/java/org/h2gis/h2spatialext/function/spatial/mesh/MeshFunctionTest.java

Use JTS instead of JDelaunay if quality constraint is not set. Currently, JTS Delaunay triangulation is more robust than JDelaunay for a set of points.
Todo in JDelaunay fix invalid mesh (triangle incircle that contains another triangle vertex)

Use JTS if delaunay of points without quality arguments

---

h2drivers/src/main/java/org/h2gis/drivers/DriverManager.java
h2drivers/src/main/java/org/h2gis/drivers/file_table/FileEngine.java
h2drivers/src/main/java/org/h2gis/drivers/geojson/GeoJsonWriteDriver.java
h2drivers/src/main/java/org/h2gis/drivers/kml/KMLWriterDriver.java
h2drivers/src/test/java/org/h2gis/drivers/geojson/GeojsonImportExportTest.java
h2drivers/src/test/java/org/h2gis/drivers/kml/KMLImporterExporterTest.java

Hi,
I have prepared DB on Win machine and then tried to transfer it to Unix hosting machine. I found that SQL in SYS.TABLES translates directory separators to platfrom specific values even when I provide slash. It shows error in log showing that file was not found and that table will be empty (org.h2gis.drivers.file_table.FileEngine#createTable).
I think that file path should be calculated when needed and not eagerly. With patch I have fixed two failing test. First is about not closing outputstream and second is about order of columns.
Take a look, and if you will like it, you could accept it.
Thx
Ivos

Unable to transfer DB created on Win to Unix machine

---

.travis.yml

Then there is no reason to try to compile with other jvm.

H2GIS JDBC is java 6 Api only.

---

h2drivers/src/main/java/org/h2gis/drivers/asciiGrid/AsciiGridReader.java

Use directly the arcgrid reader instead of using JAI Api. Arcgrid reader was already casted, then there is no added dependency.

Do not rely on JAI Op for arcgrid driver (OSGi issues)

---

h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/raster/ST_D8FlowAccumulation.java
h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/raster/ST_Extrema.java
h2spatial-ext/src/main/java/org/h2gis/h2spatialext/jai/NoDataROI.java
h2spatial-ext/src/main/java/org/h2gis/h2spatialext/jai/RangeFilterOpImage.java

ROI does not handle very well the method .getAsRectangleList() used by ExtremaOP.
- Then instead of defining a ROI for Min/Max all NoData are replace by a value found in the input raster.
- Constant image use RenderingHints of georaster in order to comply with Tile size.
TODO, implement our own speed-up implementation of getAsRectangleList() as soon as vectorization will be done. Because we will use an optimized maximum rectangle creator combined with iterator (on demand). See http://www.geeksforgeeks.org/largest-rectangle-under-histogram/

Speed-up extrema by not using ROI

---

doxygen/h2gis.conf

Using `sed` command, the config file will be updated setting the right version of H2GIS documentation.

Add key word for writing config file

---

h2drivers/src/main/java/org/h2gis/drivers/asciiGrid/AsciiGridReader.java
h2drivers/src/main/java/org/h2gis/drivers/asciiGrid/AsciiGridWriter.java
h2drivers/src/main/java/org/h2gis/drivers/asciiGrid/ST_AsciiGridRead.java
h2drivers/src/test/java/org/h2gis/drivers/asciiGrid/AsciiGridImportExportTest.java

WKB Raster is upper left based and Ascii driver is lower left based. Fix the driver to place the raster at the right position.

Fix Ascii driver envelope computation

---

_config.yml
index.html

Update homepage to change the release number and update configuration file to replace irstv link with the appropriate one

Update homepage and configuration file

---

h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMParser.java
h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMRead.java
h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMTablesFactory.java
h2gis-functions/src/test/java/org/h2gis/functions/io/osm/OSMImportTest.java
h2gis-utilities/src/main/java/org/h2gis/utilities/TableUtilities.java

Now the user is able to add an option to drop the existing OSM tables

Extend the OSM driver with an option to delete the existing osm tables.

---

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java
h2gis-functions/src/main/java/org/h2gis/functions/system/H2GISversion.java
h2gis-functions/src/main/resources/org/h2gis/functions/system/version.txt
h2gis-functions/src/test/java/org/h2gis/functions/system/SystemFunctionTest.java

A function to return the current H2GIS version.
The version is stored in the version.txt file. It 's stored in the /org/h2gis/functions/system/version.txt resources folder.

H2GISVersion function

---

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/clean/MakeValidOp.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/clean/ST_MakeValid.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunction2Test.java

About  #777
This PR proposes a new function to make a geometry valid.
The function is based on the @mukoki code
Thanks a lot to him that permits to integrate its code in H2GIS.

ST_MakeValid function

---

pom.xml

**Bugs**
- Read the prj file and set the SRID from FILE_TABLE interface
- Align ST_NumInteriorRing to SQL/MM
- ST_Length works only with Line, Curve and MultiLine and MultiCurve.
- Fixes on GeoJSON driver
**Enhancements**
- ST_Graph() is now compatible with a PostGIS database
- Add ST_Expand() support distance for X and Y
- Update to JTS 1.14
- Update to H2 1.4.193
- CSV, OSM and GPX drivers support options (encoding, field separators, delete existing tables...)
- Add cancel action on the CSV driver
- ST_OSMDOWNLOADER supports a delete argument to remove the downloading file
**Features**
- H2GISversion() returns the H2GIS version
- ST_Collect() is an alias of ST_Accum()
- Add ST_NPoints() and fix ST_NumPoints() to be conform to SQL/MM
- Add TSV importer and exporter drivers and functions …

Prepare H2GIS 1.3.1 release

---

h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonField.java

Some fields will only be used by GeoJSON files of the 2008 specification.
("CRS", "CRS_URN_EPSG", "CRS_URN_OGC": These fields are no longer useful for the new standard RFC 7946 because it uses WGS 84 by default.
"LINK": link object doesn't exist in RFC 7946.)
Although, these fields will be kept for compatibility reasons and indicated "2008" in comment.
New field "BBOX" is added for interoperability.

Update GeoJsonField class

---

pom.xml

Fixes the warning on jenkins because of the relativePath.

Fixes the warning on jenkins because of the relativePath. 

---

h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java
h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonReaderDriver.java
h2gis-functions/src/main/java/org/h2gis/functions/io/gpx/GPXDriverFunction.java
h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMDriverFunction.java
h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMParser.java
h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMRead.java
h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFImportExportTest.java
h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java
h2gis-functions/src/test/java/org/h2gis/functions/io/tsv/TSVDriverTest.java
h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java

To avoid interrupting the processing chains, an empty table is created when the file read by the driver is empty. 
Add unit tests

Create empty table when the file is empty

---

h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMParser.java
h2gis-functions/src/main/java/org/h2gis/functions/io/osm/OSMTablesFactory.java
h2gis-functions/src/test/java/org/h2gis/functions/io/osm/OSMImportTest.java

The table tag has been removed to follow the OSM XML model.
Now, a tag (key, value tupple) is stored in the  column names TAG_KEY, TAG_VALUE.
Namely the tables NODE_TAG, WAY_TAG and RELATION_TAG
see #923

Improve OSM reader

---

h2gis-dist/src/main/assembly/bin.xml

Fix the standalone build to remove not used dependencies.
Should be merged after orbisgis/orbisgis-parents#31

Fix the standalone build to remove not used dependencies.

---

h2gis-functions/src/main/java/org/h2gis/functions/io/kml/KMLDriverFunction.java
h2gis-functions/src/main/java/org/h2gis/functions/io/kml/KMLWriterDriver.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Explode.java
h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java
h2gis-functions/src/test/java/org/h2gis/functions/io/json/JsonImportExportTest.java
h2gis-functions/src/test/java/org/h2gis/functions/io/kml/KMLImporterExporterTest.java
h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java
h2gis-functions/src/test/java/org/h2gis/functions/io/tsv/TSVDriverTest.java

Ensure that all SQL IO writer functions are able to run a select.
Note : The query  must be surrounded by parentheses.
Examples
```SQL
CALL SHPWRITE('/tmp:myfile.shp', '(SELECT ST_BUFFER(the_geom, 12) as the_geom from geoTable where id > 12)');
CALL GEOJSONWRITE('/tmp:myfile.geojson', '(SELECT ST_BUFFER(the_geom, 12) as the_geom from geoTable where id > 12)');
CALL JSONWRITE('/tmp:myfile.json', '(SELECT ST_BUFFER(the_geom, 12) as the_geom from geoTable where id > 12)');
CALL TSVWRITE('/tmp:myfile.tsv', '(SELECT ST_BUFFER(the_geom, 12) as the_geom from geoTable where id > 12)');
```

Improve SQL writer driver function

---

h2gis-functions/src/main/java/org/h2gis/functions/spatial/clean/MakeValidOp.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/clean/ST_MakeValid.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/clean/ST_MakeValidTest.java

ST_MakeValid on flat polygon with preserveGeoDim to true returns an empty polygon and with preserveGeoDim to false returns a multilinestring.
Liked to the issue #1020.

Fix ST_MakeValid on flat Polygon

---

h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/UpdateGeometrySRID.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java
h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryMetaData.java
h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java

UpdateSRID function

---

h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
h2gis-utilities/src/main/resources/META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule
h2gis-utilities/src/test/java/org/h2gis/utilities/JDBCUtilitiesTest.java

Adds to the `JDBCUtilities` class different index related methods : 
- createIndex/createSpatialIndex
- dropIndex
- isIndexed, isSpatialIndexed
Each methods signature is doubled : one for the table name as `String`, an other for the table name as `TableLocation`.

Add utilities for indexes.

---

h2gis-functions/src/main/java/org/h2gis/functions/spatial/generalize/ST_PrecisionReducer.java

so if we have a topology exception then return the input geometry

PrecisionReducer is less tolerant since 1.18.0

---

h2gis-functions/src/main/java/org/h2gis/functions/io/utility/IOMethods.java
h2gis-functions/src/test/java/org/h2gis/functions/utility/IOMethodsTest.java

When the table source doesn't contain any rows an empty table must be created

Fix a bug in exportToDatabase 

---

h2gis-functions/src/test/java/org/h2gis/functions/spatial/topography/TopographyTest.java

Several flaky tests are found in this project and this PR proposes to fix them.
1. How to reproduce the flaky tests
- The project is built and tested under `javaJDK8`.
- The tool used for the flaky test detection is [NonDex](https://github.com/TestingResearchIllinois/NonDex).
- I ran `mvn -pl h2gis-functions edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.h2gis.functions.spatial.topography.TopographyTest`, which produced
> [ERROR] Failures: 
> [ERROR]   TopographyTest.testST_TriangleContouringWithColumns:273 expected: <-6.86> but was: <-1.514117647058825>
> [ERROR]   TopographyTest.testST_TriangleContouringWithZ:215 expected: <-6.4> but was: <-1.514117647058825>
> [ERROR]   TopographyTest.testST_TriangleContouringWithZDoubleRange:318 expected: <-6.86> but was: …

fix three flaky tests in TopographyTest

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/io/dbf/DBFDriverFunction.java
h2gis-functions/src/main/java/org/h2gis/functions/io/geojson/GeoJsonWriteDriver.java
h2gis-functions/src/main/java/org/h2gis/functions/io/kml/KMLWriterDriver.java
h2gis-functions/src/main/java/org/h2gis/functions/io/utility/IOMethods.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Explode.java
h2gis-functions/src/test/java/org/h2gis/functions/io/geojson/GeojsonImportExportTest.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/metadata/GeometryTableUtilsTest.java
h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryMetaData.java
h2gis-utilities/src/main/java/org/h2gis/utilities/GeometryTableUtilities.java
h2gis-utilities/src/main/java/org/h2gis/utilities/JDBCUtilities.java
h2gis-utilities/src/main/java/org/h2gis/utilities/TableUtilities.java
h2gis-utilities/src/main/java/org/h2gis/utilities/wrapper/SpatialResultSetMetaDataImpl.java
pom.xml

Related to https://github.com/orbisgis/h2gis/issues/1236
Note that there are some issues with the ST_EXPLODE function that uses the SimpleResult.
It seems that H2 doesn't recognize a geometry column build with the following properties : 
```java
rs.addColumn(columnName, metadata.getColumnType(i),
type, metadata.getPrecision(i), metadata.getScale(i));
```
where 
columnName =  the_geom
metadata.getColumnType(i) = 1111
type = GEOMETRY(MULTIPOLYGON)
metadata.getPrecision(i)= 1048576
metadata.getScale(i) = 0
Link to the code : https://github.com/ebocher/H2GIS/blob/H2_204/h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Explode.java#L292
We must investigate.
@katzyn

Update H2GIS to support H2 2.0.204

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_AsEWKB.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/convert/GeometryConvertTest.java

Add ST_AsEWKB function

---

.github/workflows/CI_snapshot.yml

Remove space in CI snapshot workflow name.

Remove space in CI snapshot workflow name.

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_DistanceSphere.java

ST_DistanceSphere throws an exception when two input geometries do not have the same srid

Fix ST_DistanceSphere

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/spatial/aggregate/ST_Accum.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_Union.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java

Filter the empty geometry set to the st_accum function to avoid srid problem because an empty geometry doesn't have any srid
Fix ST_Union when the first and the second geometries are empty

Fix ST_ACCUM and ST_Union with empty geom

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_Union.java

Do not use UnionCoverage with ST_Union because the input geometries must be correctly noded.
See the figures.
Input geometry
UnionCoverage output
Robust union overlay output

Rebase ST_Union

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MakeArcLine.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MakeArcPolygon.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MakeEllipse.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/create/CreateFunctionTest.java

This PR adds two function to create an elliptical arc as line or polygon from a given point, a distance, a start angle and the size of it in radians.
Fix ST_MakeEllipse to keep the srid of the centre point
Exemple : 
```sql 
SELECT ST_ACCUM(the_geom) from (SELECT ST_MakeArcPolygon('POINT (0 0)'::GEOMETRY,  X*10, 
CASE WHEN X=1 THEN 0 ELSE PI()/X END, PI()/X+1) as the_geom 
FROM generate_series(1, 3)) as foo
```

Add two functions to create an elliptical arc as line or polygon.

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MinimumBoundingRadius.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/create/CreateFunctionTest.java

ST_MinimumBoundingRadius is a table function. The signature is the same as in PostGIS.
SELECT ST_AsText(center), radius FROM ST_MinimumBoundingRadius('POLYGON((26426 65078,26531 65242,26075 65136,26096 65427,26426 65078))');

Add ST_MinimumBoundingRadius function

---

docs/CHANGELOG.md
h2gis-dist/pom.xml
h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFEngineTest.java
h2gis-functions/src/test/java/org/h2gis/functions/io/dbf/DBFImportExportTest.java

- Fix the test `DBFEngineTest.readDBFRussianWrongEncodingThenWriteThenRead()` which was failing when it is run twice without cleaning the `target/` folder
- Fix the test `DBFImportExportTest.testWriteDecimal()` which was failing under windows because when the whole class is run, the file `target/area_export2.dbf` stay in use and isn't accessible to this test.
- When the `h2gis-dist` jar is run, in the browser, it was not possible to create a new database like in the `h2` jar. The main class in the h2 pom is `org.h2.tools.Console` instead of `org.h2.tools.Server`

Fix failing test on windows and 'h2gis-dist' execution

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/generalize/ST_SnapToGrid.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/processing/ProcessingFunctionTest.java

A single SnapToGrid function that reduces the precision of the geometry according a grid size

SnapToGrid function

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java
h2gis-functions/src/main/java/org/h2gis/functions/spatial/snap/ST_SnapToSelf.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/processing/ProcessingFunctionTest.java

A function to snap a geometry to itself
```sql
SELECT ST_SnapToSelf('POLYGON ((0 0, 1 1, 2 1, 3 0.5, 2 -3, 3 0.499, 0 0))'::GEOMETRY, 0.001)
```
Input
Output

Add ST_SnapToSelf function

---

docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Extent.java
h2gis-functions/src/test/java/org/h2gis/functions/spatial/SpatialFunctionTest.java

Fix mixed srid error on empty geometry with ST_Extent about #1400
Added a unit test for regression

Fix mixed srid error on empty geometry with ST_Extent about #1400

---

docs/CHANGELOG.md
h2gis-functions/pom.xml

Remove transitive dependency of flatgeobuff that use an old version of jts 
about https://github.com/dbeaver/dbeaver/issues/37093

Fix duplicate dependency version issue (JTS 1.19 and 1.20)

---

docs/CHANGELOG.md
h2gis-functions/pom.xml
pom.xml

Update version of flatgeobuf, use the maven version range in order to upgrade up to (excluded) major version of flat geo buffer driver

Update version of flat geo buf

---

.gitignore
docs/CHANGELOG.md
h2gis-functions/src/main/java/org/h2gis/functions/io/fgb/FGBWriteDriver.java
h2gis-functions/src/test/java/org/h2gis/functions/io/fgb/FGBImportExportTest.java

For unknown reason, byte and boolean were stored using Short type (2 bytes instead of 1)

Fix storage of Byte and Boolean type in FGB Driver
